trigger: none

pool:
  name: self
  

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Install Angular cli"
  inputs:
    command: "custom"
    customCommand: "install -g @angular/cli"
  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'React,node-express,sql/vivant-ui'

- task: CmdLine@2
  inputs:
    script: 'npm install karma-junit-reporter --save-dev'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'React,node-express,sql/vivant-ui'
    customCommand: 'run build'
    
- task: CmdLine@2
  displayName: "Run Angular tests"
  inputs:
    script: |
      ng test --browsers=ChromeHeadless --code-coverage --watch=false
    workingDirectory: 'React,node-express,sql/vivant-ui'
  
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'coverage/ang-products/unit-test-result.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/React,node-express,sql/vivant-ui/coverage/ang-products/'

  
- task: CmdLine@2
  inputs:
    script: |
      mv Dockerfile dist/ang-products/
    workingDirectory: 'React,node-express,sql/vivant-ui'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/React,node-express,sql/vivant-ui/dist/'
    ArtifactName: 'MyArtifact'
    publishLocation: 'Container'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  inputs:
   script: |
     cd React,node-express,sql/vivant-ui/dist/ang-products
     sudo docker build -t bhanu8808/finalvivant-ui .
     sudo docker login -u bhanu8808 -p Bhanu@1432
     sudo docker push bhanu8808/finalvivant-ui
- task: CmdLine@2
  inputs:
    script: |
      cd React,node-express,sql/vivant-backend/
      sudo docker build -t bhanu8808/finalvivanth-backend .
      sudo docker push bhanu8808/finalvivanth-backend
- task: CmdLine@2
  inputs:
   script: 'mv terraform MongoDBAngular13/dist/mongo-dbangular13'
