---
jobs:
  - job: MyJob
    displayName: My Job
    pool:
      name: self
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: Install Node.js
      - task: Npm@1
        displayName: Install Angular
        inputs:
          command: custom
          customcommand: install -g @angular/cli
      - task: Npm@1
        inputs:
          command: install
          workingDir: React,node-express,sql/vivant-ui
      - task: CmdLine@2
        inputs:
          script: npm install karma-junit-reporter --save-dev
      - task: Npm@1
        inputs:
          command: custom
          workingDir: React,node-express,sql/vivant-ui
          customCommand: run build
      - task: CmdLine@2
        displayName: Run Angular tests
        inputs:
          script: |
            cd React,node-express,sql/vivant-ui
            npm test
            #workingDirectory: 'React,node-express,sql/vivant-ui'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/coverage/ang-products-*.xml'
          searchFolder: '''$(System.DefaultWorkingDirectory)/React,node-express,sql/vivant-ui/coverage/ang-products'
          
      # - task: PublishTestResults@2
      #   inputs: testResultsFormat: 'JUnit'
      #     testResultsFiles: 'testresults/junit/unit-test-result.xml'
      #     searchFolder: '$(System.DefaultWorkingDirectory)/React,node-express,sql/vivant-ui/'
      #     mergeTestResults: true testRunTitle: 'Angular Tests'
      - task: CmdLine@2
        inputs:
          script: |
            cd React,node-express,sql
            mv Dockerfile React,node-express,sql/dist
      - task: DockerInstaller@0
        inputs:
          dockerVersion: 17.09.0-ce
      - task: CmdLine@2
        inputs:
          script: |
            cd React,node-express,sql/vivant-ui/dist/React,node-express,sql
            docker build -t 
            docker push
            docker push
      - task: CmdLine@2
        inputs:
          script: |
            cd React,node-express,sql/vivant-ui/dist/React,node-express,sql
            docker build -t
            docker push
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.SourcesDirectory)/React,node-express,sql/dist/
          ArtifactName: MyArtifact
          publishLocation: container
